// Developer Express Code Central Example:
// How to convert an XtraGrid to an XtraReport at runtime
// 
// This example demonstrates how to dynamically create a report based upon the
// GridControl at runtime. This means that all filtering and sorting conditions
// selected in the grid are also applied in a report. To accomplish this task, it
// is necessary to create a report with all the necessary bands, bind it to a data
// source and adjust all the necessary options.
// 
// You can find sample updates and versions for different programming languages here:
// http://www.devexpress.com/example=E108

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dxKB17175.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Provider=Microsoft.Jet.OLEDB.4.0;Data Source=\"..\\..\\nwind.mdb\"")]
        public string nwindConnectionString {
            get {
                return ((string)(this["nwindConnectionString"]));
            }
        }
    }
}
